github: [JokerApocalypse]
patreon: drxenon
open_collective: xenonxmd
ko_fi: drxenon
tidelift: npm/xenon-xmd
community_bridge: xenon-foundation
liberapay: drxenon
issuehunt: xenonxmd
lfx_crowdfunding: xenon-xmd-project
polar: drxenon
buy_me_a_coffee: drxenon
thanks_dev: drxenon
custom:
  - https://wa.me/2250500107362
  - https://youtube.com/@Dr.Xenon2
  - https://ko-fi.com/drxenon
  - https://github.com/JokerApocalypse/XENON-XMD
